--- Generated by: ChatGPT

---@class base46.colors
local M = {}

M.none = 'NONE'

M.accent = {
  yellow = '#E5C07B',
  cyan = '#56b6c2',
  blue = '#61AFEF',
  darkblue = '#528BFF',
  green = '#98C379',
  orange = '#D19A66',
  violet = '#C678DD',
  magenta = '#E06C75',
  red = '#E06C75',
}

M.base_30 = {
  base00 = '#1C1E26', -- Default background
  base01 = '#191a22', -- Float background
  base02 = '#1A1C23', -- Statusline background
  base03 = '#4B5263', -- WinSeparator, Border
  base04 = '#ABB2BF', -- Statusline foreground
  base05 = '#D0D0D0', -- Default Foreground, Caret, Delimiters, Operators
  base06 = '#98C379', -- Diff Added
  base07 = '#E5C07B', -- Diff Modified
  base08 = '#BF616A', -- Diff Deleted
  base09 = '#B48EAD', -- Diagnostic Info, Hint
  base0A = '#D08770', -- Diagnostic Warning
  base0B = '#E06C75', -- Diagnostics Error
  base0C = '#56b6c2', -- Markup Bold
  base0D = '#C678DD', -- Markup Italic
  base0E = '#61AFEF', -- Markup url
  base0F = '#E5C07B', -- Markup Inline Code
  base0G = '#D19A66', -- Markup Heading 1
  base0H = '#98C379', -- Markup Heading 2
  base0I = '#EBCB8B', -- Markup Heading 3
  base0J = '#BF616A', -- Markup Heading 4
  base0K = '#98C379', -- Markup Heading 5
  base0L = '#E06C75', -- Markup Heading 6
  base0M = '#C678DD', -- Markup Tag
  base0N = '#E5C07B', -- Markup Tag Attribute
  base0O = '#C678DD', -- Markup Tag Delimiter
  base0P = '#C678DD', -- Pmenu Background
  base0Q = '#528BFF', -- Folder Background
  base0R = '#528BFF', -- Cursor Color
  base0S = '#BF616A', -- Accent, can be used as primary color
  base0T = '#D19A66', -- Title
}

M.base_16 = {
  base00 = '#4B5263', -- Default Background
  base01 = '#2E303E', -- Lighter Background (folding marks)
  base02 = '#3B3F51', -- Selection, Visual Background
  base03 = '#4B5263', -- Comments, Invisibles, Line Highlighting
  base04 = '#E06C75', -- Variable Parameter
  base05 = '#ABB2BF', -- Caret, Delimiters, Operators
  base06 = '#e06c75', -- Property, Variable Member
  base07 = '#C678DD', -- PreProc, Include, Define, Macro, PreCondit
  base08 = '#E06C75', -- Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
  base09 = '#D19A66', -- Integers, Boolean, Constants, XML Attributes, Markup Link Url
  base0A = '#E5C07B', -- Classes, Markup Bold, Search Text Background
  base0B = '#98C379', -- Strings, Inherited Class, Markup Code, Diff Inserted
  base0C = '#56b6c2', -- Support, Regular Expressions, Escape Characters, Markup Quotes
  base0D = '#61AFEF', -- Functions, Methods, Attribute IDs, Headings
  base0E = '#C678DD', -- Keywords, Storage, Selector, Markup Italic, Diff Changed
  base0F = '#C678DD', -- Opening/Closing Embedded Language Tags, e.g. `<?php ?>`
}

M.groups = {}

return M
