--- Generated by: ChatGPT

---@class base46.colors
local M = {}

M.none = 'NONE'

M.accent = {
  yellow = '#F0C674',
  cyan = '#8ABEB7',
  blue = '#81A2BE',
  darkblue = '#223B54',
  green = '#B5BD68',
  orange = '#DE935F',
  violet = '#85678F',
  magenta = '#B294BB',
  red = '#CC6666',
}

M.base_30 = {
  base00 = '#181818', -- Default background
  base01 = '#121212', -- Float background
  base02 = '#121212', -- Statusline background
  base03 = '#585858', -- WinSeparator, Border
  base04 = '#B8B8B8', -- Statusline foreground
  base05 = '#E8E8E8', -- Default Foreground, Caret, Delimiters, Operators
  base06 = '#A1B56C', -- Diff Added
  base07 = '#F7CA88', -- Diff Modified
  base08 = '#DC9656', -- Diff Deleted
  base09 = '#8ABEB7', -- Diagnostic Info, Hint
  base0A = '#F0C674', -- Diagnostic Warning
  base0B = '#CC6666', -- Diagnostics Error
  base0C = '#B5BD68', -- Markup Bold
  base0D = '#85678F', -- Markup Italic
  base0E = '#81A2BE', -- Markup url
  base0F = '#DE935F', -- Markup Inline Code
  base0G = '#F0C674', -- Markup Heading 1
  base0H = '#A1B56C', -- Markup Heading 2
  base0I = '#F7CA88', -- Markup Heading 3
  base0J = '#DC9656', -- Markup Heading 4
  base0K = '#8ABEB7', -- Markup Heading 5
  base0L = '#DE935F', -- Markup Heading 6
  base0M = '#CC6666', -- Markup Tag
  base0N = '#B294BB', -- Markup Tag Attribute
  base0O = '#CC6666', -- Markup Tag Delimiter
  base0P = '#85678F', -- Pmenu Background
  base0Q = '#85678F', -- Folder Background
  base0R = '#A1B56C', -- Cursor Color
  base0S = '#85678F', -- Accent, can be used as primary color
  base0T = '#DE935F', -- Title
}

M.base_16 = {
  base00 = '#585858', -- LineNr
  base01 = '#282828', -- Lighter Background (folding marks)
  base02 = '#383838', -- Selection, Visual Background
  base03 = '#585858', -- Comments, Invisibles, Line Highlighting
  base04 = '#DE935F', -- Variable Parameter
  base05 = '#E8E8E8', -- Caret, Delimiters, Operators
  base06 = '#CC6666', -- Property, Variable Member
  base07 = '#B294BB', -- PreProc, Include, Define, Macro, PreCondit
  base08 = '#CC6666', -- Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
  base09 = '#DE935F', -- Integers, Boolean, Constants, XML Attributes, Markup Link Url
  base0A = '#F0C674', -- Classes, Markup Bold, Search Text Background
  base0B = '#B5BD68', -- Strings, Inherited Class, Markup Code, Diff Inserted
  base0C = '#8ABEB7', -- Support, Regular Expressions, Escape Characters, Markup Quotes
  base0D = '#81A2BE', -- Functions, Methods, Attribute IDs, Headings
  base0E = '#B294BB', -- Keywords, Storage, Selector, Markup Italic, Diff Changed
  base0F = '#B294BB', -- Opening/Closing Embedded Language Tags, e.g. `<?php ?>`
}

M.groups = {}

return M
