local normal = {
  mode = { 'n' },
  { '<leader>w', '<cmd>update<cr>', desc = 'save file' },
  { '<leader>q', '<cmd>quit<cr>', desc = 'exit' },
  { '<leader>s', '<cmd>split<cr>', desc = 'split window hori' },
  { '<leader>v', '<cmd>vsplit<cr>', desc = 'split window vert' },
  { '<c-x>', group = 'Emacs Shortcuts' },
  { '<c-x>o', '<c-w>w<cr>', desc = 'next window' },
  { '<c-x>r', '<c-w>r<cr>', desc = 'rotate windows' },
  { '<c-x>2', '<cmd>split<cr>', desc = 'split window vert' },
  { '<c-x>3', '<cmd>vsplit<cr>', desc = 'split window hori' },
  { '<c-x>c', '<cmd>qa<cr>', desc = 'exit neovim' },
  { '<c-x>b', '<cmd>Neotree source=buffers float focus toggle<cr>', desc = 'list buffers' },
  { '<c-x><c-d>', '<cmd>Dired<cr>', desc = 'file manager' },
  { '<c-x><c-f>', ':find ', desc = 'find file' },
  { '<c-x><c-s>', '<cmd>write<cr>', desc = 'save' },
  { '<c-h>', group = 'Help' },
  { '<c-h>h', '<cmd>help<cr>', desc = 'help' },
  { '<c-h><c-t>', '<cmd>h tutor<cr>', desc = 'tutor for beginners' },
  { '<c-h>m', '<cmd>h user-manual<cr>', desc = 'user-manual' },
  { '<c-h>l', '<cmd>ShowkeysToggle<cr>', desc = 'show keys pressed' },
  { '<c-h>t', '<cmd>Typr<cr>', desc = 'show keys pressed' },
  { '<c-h>T', '<cmd>TyprStats<cr>', desc = 'show keys pressed' },
  { '<c-h>o', '<cmd>h option-list<cr>', desc = 'option list for config neovim' },
  { '<c-h>p', '<cmd>TimerlyToggle<cr>', desc = 'timerly' },
  { '<leader>l', group = 'Lazy' },
  { '<leader>lp', '<cmd>Lazy profile<cr>', desc = 'profile' },
  { '<leader>lh', '<cmd>Lazy home<cr>', desc = 'home' },
  { '<leader>lu', '<cmd>Lazy update<cr>', desc = 'update' },
  { '<leader>lr', '<cmd>Lazy restore<cr>', desc = 'restore' },
  { '<leader>c', group = '(LSP) Code' },
  { '<leader>ch', vim.lsp.buf.hover, desc = 'hover' },
  { '<leader>ca', vim.lsp.buf.code_action, desc = 'action' },
  { '<leader>cd', vim.lsp.buf.definition, desc = 'definition' },
  { '<leader>ci', vim.lsp.buf.implementation, desc = 'implementation' },
  { '<leader>ct', vim.lsp.buf.type_definition, desc = 'type definition' },
  { '<leader>cr', vim.lsp.buf.rename, desc = 'rename' },
  { '<leader>cs', vim.lsp.buf.document_symbol, desc = 'document symbol' },
  { '<leader>cm', '<cmd>Man<cr>', desc = 'man' },
  { '<leader>cf', '<cmd>Conform<cr>', desc = 'format' },
  { '<leader>d', group = '(LSP) Diagnostics' },
  { '<leader>do', vim.diagnostic.open_float, desc = 'open float' },
  { '<leader>dl', vim.diagnostic.setloclist, desc = 'list of diagnostics' },
  {
    '<leader>dn',
    function()
      vim.diagnostic.jump { count = 1, float = true }
    end,
    desc = 'next',
  },
  {
    '<leader>dp',
    function()
      vim.diagnostic.jump { count = -1, float = true }
    end,
    desc = 'prev',
  },
  { '<leader>g', group = 'GitSigns' },
  { '<leader>m', group = 'Mason' },
  { '<leader>x', group = 'Toggleterm' },
}

return {
  normal,
}
