local keymap = require 'utils.keymap'
local nmap = keymap.nmap
local tmap = keymap.tmap

nmap('<leader>', '<Nop>')
nmap('<C-x>', '<cmd>bd<CR>')
nmap('+', '<C-a>')
nmap('-', '<C-x>')
nmap('ss', '<cmd>split<CR>')
nmap('sv', '<cmd>vsplit<CR>')
nmap('<F7>', '<cmd>Inspect<CR>')
nmap('<F8>', '<cmd>InspectTree<CR>')
nmap('f', '=<CR>')
nmap('F', '=G<CR>')
nmap('s', '<cmd>HopWord<CR>')
nmap('<C-Left>', '<cmd>TabuPrev<CR>')
nmap('<C-Right>', '<cmd>TabuNext<CR>')
nmap('<C-Up>', '<cmd>TabuCloseAll<CR>')
nmap('<C-Down>', '<cmd>TabuClose<CR>')
nmap('<Tab>', '<cmd>lua require("nvim-window").pick()<CR>')
nmap('[s', '[s<cmd>Telescope spell_suggest theme=cursor<CR>')
nmap(']s', ']s<cmd>Telescope spell_suggest theme=cursor<CR>')
nmap(';', '<S-A>;<ESC><cmd>update<CR>')
tmap('<ESC>', '<c-c> exit<CR>')
nmap('<C-t>', '<cmd>MenuOpen<CR>')
nmap('<RightMouse>', '<cmd>MenuTreeOpen<CR>')
