#!/bin/bash

# Define the weather codes
declare -A WEATHER_CODES=(
  ["113"]="☀️ "
  ["116"]="⛅ "
  ["119"]="☁️ "
  ["122"]="☁️ "
  ["143"]="☁️ "
  ["176"]="🌧️"
  ["179"]="🌧️"
  ["182"]="🌧️"
  ["185"]="🌧️"
  ["200"]="⛈️ "
  ["227"]="🌨️"
  ["230"]="🌨️"
  ["248"]="☁️ "
  ["260"]="☁️ "
  ["263"]="🌧️"
  ["266"]="🌧️"
  ["281"]="🌧️"
  ["284"]="🌧️"
  ["293"]="🌧️"
  ["296"]="🌧️"
  ["299"]="🌧️"
  ["302"]="🌧️"
  ["305"]="🌧️"
  ["308"]="🌧️"
  ["311"]="🌧️"
  ["314"]="🌧️"
  ["317"]="🌧️"
  ["320"]="🌨️"
  ["323"]="🌨️"
  ["326"]="🌨️"
  ["329"]="❄️ "
  ["332"]="❄️ "
  ["335"]="❄️ "
  ["338"]="❄️ "
  ["350"]="🌧️"
  ["353"]="🌧️"
  ["356"]="🌧️"
  ["359"]="🌧️"
  ["362"]="🌧️"
  ["365"]="🌧️"
  ["368"]="🌧️"
  ["371"]="❄️"
  ["374"]="🌨️"
  ["377"]="🌨️"
  ["386"]="🌨️"
  ["389"]="🌨️"
  ["392"]="🌧️"
  ["395"]="❄️ "
)

# Make a request to wttr.in and store the response in a variable
weather=$(curl -s 'https://wttr.in/?format=j1')

# Parse the JSON response to get the current weather data
weather_code=$(echo "$weather" | jq -r '.current_condition[0].weatherCode' 2>/dev/null)

if [ -z "$weather_code" ]; then
  echo "{\"text\":\"⛅\"}"
else
  feels_like=$(echo "$weather" | jq -r '.current_condition[0].FeelsLikeC')

  # Format the weather data
  tempint=$(echo "$feels_like" | cut -d. -f1)
  extrachar=''
  if [[ $tempint -gt 0 && $tempint -lt 10 ]]; then
    extrachar='+'
  fi
  text=$(printf " %s%s°C" "${WEATHER_CODES[$weather_code]}" "$extrachar$feels_like")

  # Print the formatted weather data as JSON
  echo "{\"text\":\"$text\"}"
fi
