set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -sa terminal-overrides ",xterm*:Tc" # tmux display things in 256 colors
set -g prefix C-a # setting the prefix from C-b to C-a
set -s escape-time 1 # setting the delay between prefix and command
set -g base-index 1 # set the base index for windows to 1 instead of 0
setw -g pane-base-index 1 # set the base index for panes to 1 instead of 0
set -g mouse on # mouse support
# enable activity alerts
setw -g monitor-activity on
set -g visual-activity on
setw -g mode-keys vi # enable vi keys

unbind C-b # Free the original C-b prefix keybinding

# reload config
bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind C-a send-prefix # ensure that wen can send ctr-a to other apps

# splitting panes
bind | split-window -h
bind - split-window -v

# quick window selection
bind -n C-S-Left previous-window
bind -n C-S-Right next-window

bind -r C-Up resize-pane -U 5
bind -r C-Right resize-pane -R 5
bind -r C-Left resize-pane -L 5
bind -r C-Down resize-pane -D 5

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection

unbind p
bind p paste-buffer

# update the status line every 60 seconds
set -g status-interval 60
# center the window list in the status line
set -g status-justify centre

# set status line's colors
set -g status-position top
set -g status-style fg=colour255,bold,bg=default
# set the color of the window list, active windows
setw -g window-status-style fg=white,bg=default
setw -g window-status-current-style fg=colour255,bold,bg=default

# colors for pane borders
setw -g pane-border-style fg=colour8
setw -g pane-active-border-style fg=white
# active pane normal, other shaded out
setw -g window-style fg=colour8
setw -g window-active-style fg=white

# visual activity
setw -g window-status-activity-style fg=cyan

# command / message line
set -g message-style fg=yellow,bold
set -g status-left-length 40
set -g status-left "#[fg=blue]█#[fg=black,bg=blue]#S#{?client_prefix, ,}#[fg=blue,bg=default]█ #[fg=colour255]#T"
set -g status-right "%d %b  %R #[fg=blue]█#[fg=black,bg=blue]#H#[fg=blue]█"

run '~/.tmux/plugins/tpm/tpm'
