vim9script

import $"{$VIMRUNTIME}/defaults.vim"
import $"{$VIMRUNTIME}/ftplugin/man.vim"
import $"{$HOME}/.vim/plugins.vim"
import $"{$HOME}/.vim/options.vim"
import $"{$HOME}/.vim/maps.vim"
import $"{$HOME}/.vim/functions.vim"
import $"{$HOME}/.vim/autocmds.vim"

if $REDSHIFT_THEME == 'dark'
    colorscheme rosepine
else
    colorscheme rosepine_dawn
    hi EndOfBuffer guifg=#faf4ed  guibg=NONE gui=NONE cterm=NONE
endif
