vim9script

import $"{$VIMRUNTIME}/defaults.vim"
import $"{$VIMRUNTIME}/ftplugin/man.vim"
import $"{$HOME}/.vim/plugins.vim"
import $"{$HOME}/.vim/options.vim"
import $"{$HOME}/.vim/maps.vim"

g:Hexokinase_highlighters = [ 'foreground' ]

colorscheme tokyonight
