foreground            #DCC68D
background            #22211E
selection_foreground  #241b2f
selection_background  #3a3833

url_color #D885A3

# black
color0  #1f1e1b
color8  #E58538

# red
color1  #de6464
color9  #de6464

# green
color2  #7B8F5A
color10 #7B8F5A

# yellow
color3  #FFCF62
color11 #FFCF62

# blue
color4  #677FA3
color12 #677FA3

# magenta
color5  #D885A3
color13 #D885A3

# cyan
color6  #677FA3
color14 #677FA3

# white
color7  #DCC68D
color15 #DCC68D

# Cursor colors
cursor            #DCC68D
cursor_text_color background

# Tab bar colors
active_tab_foreground   #FFCF62
active_tab_background   #22211E
inactive_tab_foreground #57554d
inactive_tab_background #1f1e1b

# Marks
mark1_foreground #1f1e1b
mark1_background #de6464

# Splits/Windows
active_border_color #FFCF62
inactive_border_color #57554d
