foreground            #839496
background            #262335
selection_foreground  #ffffff
selection_background  #042E48

url_color #8be9fd

# black
color0  #21222c
color8  #6272a4

# red
color1 #fe4450
color9 #ff8b39

# green
color2 #72f1b8
color10 #72f1b8

# yellow
color3 #ffefae
color11 #ffefae

# blue
color4 #2075c7
color12 #2075c7

# magenta
color5 #d33682
color13 #d33682

# cyan
color6 #2aa198
color14 #2aa198

# white
color7  #ffffff
color15 #ffffff

# Cursor colors
cursor            #f97e72
cursor_text_color background

# Tab bar colors
active_tab_foreground   #262335
active_tab_background   #ffffff
inactive_tab_foreground #Ffffff
inactive_tab_background #241B2F

# Marks
mark1_foreground #2075c7

# Splits/Windows
active_border_color #ffffff
inactive_border_color #241b2f
