foreground            #f8f8f2
background            #22212D
selection_foreground  #ffffff
selection_background  #454158

url_color #80FFEA

# black
color0  #0B0B0F
color8  #7970A9

# red
color1  #FF9580
color9  #ff6e6e

# green
color2  #8AFF80
color10 #69ff94

# yellow
color3  #FFFF80
color11 #ffffa5

# blue
color4  #9580FF
color12 #d6acff

# magenta
color5  #FF80BF
color13 #ff92df

# cyan
color6  #80FFEA
color14 #a4ffff

# white
color7  #f8f8f2
color15 #ffffff

# Cursor colors
cursor            #9580FF
cursor_text_color background

# Tab bar colors
active_tab_foreground   #22212C
active_tab_background   #9580FF
inactive_tab_foreground #F8F8F2
inactive_tab_background #7970A9

# Marks
mark1_foreground #282a36
mark1_background #ff5555

# Splits/Windows
active_border_color #f8f8f2
inactive_border_color #6272a4
