#!/usr/bin/env bash

function set_light_wallpaper {
	feh --bg-fill --random /home/milianor/Imagens/wallpaper/light
	# notify-send --expire-time=5000 "RedShift" "It's daytime"
	ln -sf "$HOME/.config/redshift/light/rosepine.toml" "$HOME/.config/alacritty/rosepine.toml"
}

function set_dark_wallpaper {
	feh --bg-fill --random /home/milianor/Imagens/wallpaper/dark
	# notify-send --expire-time=5000 "RedShift" "It's night time"
	ln -sf "$HOME/.config/redshift/dark/rosepine.toml" "$HOME/.config/alacritty/rosepine.toml"
}

if [[ "$1" = period-changed ]]; then
	case "$3" in
	daytime)
		set_light_wallpaper
		;;
	night)
		set_dark_wallpaper
		;;
	*)
		set_dark_wallpaper
		;;
	esac

fi
