#!/usr/bin/env bash

function set_light_theme {
	ln -sf "$HOME/.config/redshift/light/settings.ini" "$HOME/.config/gtk-3.0/settings.ini"
}

function set_dark_theme {
	ln -sf "$HOME/.config/redshift/dark/settings.ini" "$HOME/.config/gtk-3.0/settings.ini"
}

if [[ "$1" = period-changed ]]; then
	case "$3" in
	daytime)
		set_light_theme
		;;
	night)
		set_dark_theme
		;;
	*)
		set_light_theme
		;;
	esac

fi
