# Set programs that you use
$terminal = foot
$filemanager = thunar
$menu = rofi
$logout_menu = wlogout
$screenshot = grim -g "$(slurp)"
$music_player = cmus-remote
$volume_control = pamixer
$HYPR_CONFIG_PATH = ~/.config/hypr/configs/

# Some default env vars.
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct # change to qt6ct if you have that

exec-once = ~/.config/hypr/scripts/wallpaper # set wallpaper
exec-once = nm-applet --indicator # Systray app for Network/Wifi
exec-once = waybar # bar
exec-once = mako # notification daemon
exec-once = cmus # music player
exec-once = /usr/lib/polkit-kde-authentication-agent-1 # authentication agent
exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data
exec-once = foot --server
exec = hyprshade on vibrance
exec-once = hyprctl setcursor Qogir-cursors $XCURSOR_SIZE

source = $HYPR_CONFIG_PATH/monitor.conf
source = $HYPR_CONFIG_PATH/variables.conf
source = $HYPR_CONFIG_PATH/workspace.conf
source = $HYPR_CONFIG_PATH/keybind.conf
