#!/bin/sh

declare wallpapers wallpaper total_wallpapers random_index

wallpapers=($HOME/wallpapers/*)
total_wallpapers=${#wallpapers[@]}
random_index=$((RANDOM % "$total_wallpapers"))
wallpaper=${wallpapers["$random_index"]}

swww img "$wallpaper" --transition-fps 60 --transition-type wipe --transition-duration 3
