#!/usr/bin/env bash

function change_bg() {
  wallpapers=($HOME/.wallpapers/*)
  total_wallpapers=${#wallpapers[@]}
  random_index=$((RANDOM % "$total_wallpapers"))
  wallpaper=${wallpapers["$random_index"]}

  bg_info=$(swww query)
  current_wallpaper="${bg_info##*:}"

  if [[ "$(basename $current_wallpaper)" = "$(basename $wallpaper)" ]]; then
    change_bg
  else
    swww img "$wallpaper" --transition-fps 60 --transition-type wipe --transition-duration 3
  fi
}

change_bg
