#!/usr/bin/env bash

source ~/.env

declare wc=(
	"☀️"
	"⛅"
	"☁️"
	"🌧️"
	"⛈️"
	"❄️"
)

declare -A WEATHER_CODES=(
	["0"]="${wc[0]}"
	["1"]="${wc[1]}"
	["2"]="${wc[1]}"
	["3"]="${wc[1]}"
	["45"]="${wc[2]}"
	["48"]="${wc[2]}"
	["51"]="${wc[3]}"
	["53"]="${wc[3]}"
	["55"]="${wc[3]}"
	["61"]="${wc[3]}"
	["63"]="${wc[3]}"
	["65"]="${wc[3]}"
	["66"]="${wc[3]}"
	["67"]="${wc[3]}"
	["71"]="${wc[5]}"
	["73"]="${wc[5]}"
	["75"]="${wc[5]}"
	["77"]="${wc[5]}"
	["80"]="${wc[3]}"
	["81"]="${wc[3]}"
	["82"]="${wc[3]}"
	["85"]="${wc[5]}"
	["86"]="${wc[5]}"
	["95"]="${wc[4]}"
	["96"]="${wc[4]}"
	["99"]="${wc[4]}"
)

# api: https://open-meteo.com/
weather=$(curl -s "https://api.open-meteo.com/v1/forecast?latitude=${LATITUDE}&longitude=${LONGITUDE}&current=temperature_2m,weather_code,is_day&timezone=auto")
weather_code=$(echo "$weather" | jq -r '.current.weather_code' 2>/dev/null)
is_day=$(echo "$weather" | jq -r '.current.is_day' 2>/dev/null)

if [ -z "$weather_code" ]; then
	echo ""
else
	if [ "$is_day" == "0" ] && [ "$weather_code" == "0" ]; then
		icon="🌙"
	else
		icon="${WEATHER_CODES[$weather_code]}"
	fi
	temp=$(echo "$weather" | jq -r '.current.temperature_2m')
	tempint=$(echo "$temp" | cut -d. -f1)
	extrachar=''
	if [[ $tempint -gt 0 && $tempint -lt 10 ]]; then
		extrachar='+'
	fi
	printf "%s %s°C" "$icon" "$extrachar$temp"
fi
