#!/bin/bash

declare wc=(
    "☀️"
    "⛅"
    "☁️"
    "🌧️"
    "⛈️"
    "☁️"
    "❄️"
)

# Define the weather codes
declare -A WEATHER_CODES=(
    ["113"]="${wc[0]}"
    ["116"]="${wc[1]}"
    ["119"]="${wc[2]}"
    ["122"]="${wc[2]}"
    ["143"]="${wc[2]}"
    ["176"]="${wc[3]}"
    ["179"]="${wc[3]}"
    ["182"]="${wc[3]}"
    ["185"]="${wc[3]}"
    ["200"]="${wc[4]}"
    ["227"]="${wc[5]}"
    ["230"]="${wc[5]}"
    ["248"]="${wc[2]}"
    ["260"]="${wc[2]}"
    ["263"]="${wc[3]}"
    ["266"]="${wc[3]}"
    ["281"]="${wc[3]}"
    ["284"]="${wc[3]}"
    ["293"]="${wc[3]}"
    ["296"]="${wc[3]}"
    ["299"]="${wc[3]}"
    ["302"]="${wc[3]}"
    ["305"]="${wc[3]}"
    ["308"]="${wc[3]}"
    ["311"]="${wc[3]}"
    ["314"]="${wc[3]}"
    ["317"]="${wc[3]}"
    ["320"]="${wc[5]}"
    ["323"]="${wc[5]}"
    ["326"]="${wc[5]}"
    ["329"]="${wc[6]}"
    ["332"]="${wc[6]}"
    ["335"]="${wc[6]}"
    ["338"]="${wc[6]}"
    ["350"]="${wc[3]}"
    ["353"]="${wc[3]}"
    ["356"]="${wc[3]}"
    ["359"]="${wc[3]}"
    ["362"]="${wc[3]}"
    ["365"]="${wc[3]}"
    ["368"]="${wc[3]}"
    ["371"]="${wc[6]}"
    ["374"]="${wc[5]}"
    ["377"]="${wc[5]}"
    ["386"]="${wc[5]}"
    ["389"]="${wc[5]}"
    ["392"]="${wc[3]}"
    ["395"]="${wc[6]}"
)

# Make a request to wttr.in and store the response in a variable
weather=$(curl -s "wttr.in/$1?format=j1")

# Parse the JSON response to get the current weather data
weather_code=$(echo "$weather" | jq -r '.current_condition[0].weatherCode' 2>/dev/null)

if [ -z "$weather_code" ]; then
    echo "{\"text\":\"⛅\"}"
else
    feels_like=$(echo "$weather" | jq -r '.current_condition[0].FeelsLikeC')

    # Format the weather data
    tempint=$(echo "$feels_like" | cut -d. -f1)
    extrachar=''
    if [[ $tempint -gt 0 && $tempint -lt 10 ]]; then
        extrachar='+'
    fi
    text=$(printf "%s%s°C" "${WEATHER_CODES[$weather_code]}" "$extrachar$feels_like")

    # Print the formatted weather data as JSON
    echo "{\"text\":\"$text\"}"
fi
