port "6601"
bind_to_address "127.0.0.1"
# Pastas de arquivos (Mude para a sua pasta de músicas)
music_directory    "~/Músicas"

playlist_directory "~/.local/share/mpd/playlists"
db_file            "~/.local/share/mpd/database"
log_file           "~/.local/share/mpd/log"
pid_file           "~/.local/share/mpd/pid"
state_file         "~/.local/share/mpd/state"
sticker_file       "~/.local/share/mpd/sticker.sql"

# Roteamento de áudio para o PipeWire
audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
}
