vim.cmd.highlight 'clear'
vim.g.c_name = 'github'

local M = {}

---@class github.palette
local c = {
  base0 = '#f0f6fc',
  base01 = '#9198a1',
  base02 = '#3e4148',
  base03 = '#282c34',
  red = '#e06c75',
  green = '#98c379',
  yellow = '#e5c07b',
  blue = '#61afef',
  purple = '#d2a8ff',
  cyan = '#a5d6ff',
  orange = '#d19a66',
  mix_red = '#5f3f47',
  mix_green = '#495948',
  mix_yellow = '#605849',
  mix_blue = '#39536c',
  mix_purple = '#5b5170',
  mix_cyan = '#4d5f70',
  mix_orange = '#5a4d43',
  git_add = '#98c379',
  git_modify = '#e5c07b',
  git_delete = '#e06c75',
  diag_info = '#61afef',
  diag_hint = '#61afef',
  diag_warning = '#e5c07b',
  diag_error = '#e06c75',
  diag_ok = '#98c379',
}

---@param group_name string
---@param group_val vim.api.keyset.highlight
local hi = function(group_name, group_val)
  local val = { fg = 'NONE', bg = 'NONE' }

  if not group_val.link then
    val = vim.tbl_extend('force', val, group_val)
    vim.api.nvim_set_hl(0, group_name, val)
  else
    vim.api.nvim_set_hl(0, group_name, group_val)
  end
end

local color = require 'utils.color'

hi('ColorColumn', { bg = c.base02 })
hi('Conceal', { fg = c.blue })
hi('CurSearch', { link = 'IncSearch' })
hi('Cursor', { fg = c.base03, bg = c.base0 })
hi('lCursor', { link = 'Cursor' })
hi('CursorIM', { link = 'Cursor' })
hi('CursorColumn', { link = 'ColorColumn' })
hi('CursorLine', { bg = c.base02 })
hi('Directory', { fg = c.blue })
hi('DiffAdd', { fg = c.git_add })
hi('DiffChange', { fg = c.git_modify })
hi('DiffDelete', { fg = c.git_delete, reverse = true })
hi('DiffText', { fg = c.cyan, reverse = true })
hi('EndOfBuffer', { fg = c.base03 })
hi('TermCursor', { link = 'Cursor' })
hi('TermCursorNC', { fg = c.base03, bg = c.base0 })
hi('ErrorMsg', { fg = c.diag_error })
hi('WinSeparator', { fg = c.base01, bg = c.base03 })
hi('Folded', { fg = c.base0, bg = c.base02 })
hi('FoldColumn', { fg = c.base0, bg = c.base03 })
hi('SignColumn', { fg = c.base01 })
hi('IncSearch', { fg = c.yellow, reverse = true })
hi('Substitute', { link = 'IncSearch' })
hi('LineNr', { fg = c.base01 })
hi('LineNrAbove', { link = 'LineNr' })
hi('LineNrBelow', { link = 'LineNr' })
hi('CursorLineNr', { fg = c.blue, bold = true })
hi('CursorLineFold', { link = 'FoldColumn' })
hi('CursorLineSign', { link = 'SignColumn' })
hi('MatchParen', { fg = c.cyan })
hi('ModeMsg', { fg = c.blue })
hi('MsgArea', { link = 'Normal' })
hi('MsgSeparator', { link = 'Normal' })
hi('MoreMsg', { link = 'ModeMsg' })
hi('NonText', { fg = c.base01 })
hi('Normal', { fg = c.base0 })
hi('NormalFloat', { fg = c.base0, bg = c.base03 })
hi('FloatBorder', { fg = c.base01, bg = c.base03 })
hi('FloatTitle', { fg = c.mix_blue, bg = c.blue, reverse = true })
hi('NormalNC', { link = 'Normal' })
hi('Pmenu', { fg = c.base0, bg = c.base03 })
hi('PmenuSel', { fg = c.blue, reverse = true })
hi('PmenuKind', { link = 'Pmenu' })
hi('PmenuKindSel', { link = 'PmenuSel' })
hi('PmenuExtra', { link = 'Pmenu' })
hi('PmenuExtraSel', { link = 'PmenuSel' })
hi('PmenuSbar', { bg = c.base03 })
hi('PmenuThumb', { bg = c.blue })
hi('Question', { fg = c.diag_info })
hi('QuickFixLine', { fg = c.base0, bg = c.base03 })
hi('Search', { fg = c.blue, bg = c.mix_blue, bold = true })
hi('SpecialKey', { link = 'NonText' })
hi('SpellBad', { underline = true, strikethrough = true })
hi('SpellCap', { fg = c.diag_hint })
hi('SpellLocal', { link = 'SpellCap' })
hi('SpellRare', { fg = c.diag_warning })
hi('StatusLine', { fg = c.base0, bg = c.base03 })
hi('StatusLineNC', { fg = c.base01, bg = c.base03 })
hi('TabLine', { fg = c.base01, bg = c.base03 })
hi('TabLineFill', { fg = c.base0, bg = c.base03 })
hi('TabLineSel', { fg = c.base0, bg = c.base03 })
hi('Title', { fg = c.blue })
hi('Visual', { fg = c.base0, bg = c.base02 })
hi('VisualNOS', { link = 'Visual' })
hi('warningMsg', { fg = c.diag_warning })
hi('Whitespace', { fg = c.base01 })
hi('WildMenu', { fg = c.base02 })
hi('WinBar', { link = 'Pmenu' })
hi('WinBarNC', { link = 'WinBar' })

hi('Comment', { fg = c.base01 })
hi('Constant', { fg = c.blue })
hi('String', { fg = c.cyan })
hi('Character', { link = 'String' })
hi('Number', { link = 'Constant' })
hi('Boolean', { link = 'Constant' })
hi('Float', { link = 'Constant' })
hi('Identifier', { fg = c.base0 })
hi('Property', { fg = c.purple })
hi('Parameter', { fg = c.blue, italic = true })
hi('Function', { fg = c.blue })
hi('Statement', { fg = c.red })
hi('Conditional', { link = 'Statement' })
hi('Repeat', { link = 'Statement' })
hi('Label', { link = 'Statement' })
hi('Operator', { link = 'Statement' })
hi('Keyword', { fg = c.red })
hi('Exception', { link = 'Statement' })
hi('Include', { link = 'Keyword' })
hi('Define', { link = 'Include' })
hi('Macro', { link = 'Include' })
hi('PreProc', { link = 'Include' })
hi('PreCondit', { link = 'Statement' })
hi('Type', { fg = c.orange })
hi('StorageClass', { link = 'Statement' })
hi('Structure', { link = 'Type' })
hi('Typedef', { link = 'Statement' })
hi('Special', { fg = c.purple })
hi('SpecialChar', { fg = c.purple })
hi('Tag', { fg = c.green })
hi('TagAttribute', { fg = c.blue })
hi('TagDelimiter', { fg = c.base0 })
hi('Delimiter', { fg = c.base0 })
hi('SpecialComment', { link = 'Statement' })
hi('Debug', { fg = c.purple })
hi('Underlined', { fg = c.purple, underline = true })
hi('Ignore', {})
hi('Error', { fg = c.diag_error, bold = true })
hi('Todo', { fg = c.blue })
hi('Added', { fg = c.git_add })
hi('Changed', { fg = c.git_modify })
hi('Removed', { fg = c.git_delete })

hi('@variable', { link = 'Identifier' })
hi('@variable.builtin', { link = 'Constant' })
hi('@variable.parameter', { link = 'Parameter' })
hi('@variable.member', { link = 'Property' })
hi('@property', { link = 'Property' })
hi('@property.json', { link = 'Keyword' })
hi('@property.yaml', { link = 'Keyword' })
hi('@constant', { link = 'Constant' })
hi('@constant.builtin', { link = 'Constant' })
hi('@constant.macro', { link = 'Constant' })
hi('@constant.html', { link = 'Tag' })
hi('@module', { link = 'Type' })
hi('@module.builtin', { link = 'Constant' })
hi('@label', { link = 'Statement' })
hi('@string', { link = 'String' })
hi('@string.documentation', { link = 'Statement' })
hi('@string.regexp', { fg = c.purple })
hi('@string.escape', { link = 'Statement' })
hi('@string.special', { link = 'Special' })
hi('@string.special.symbol', { link = 'Identifier' })
hi('@string.special.url', { link = 'Underlined' })
hi('@character', { link = 'Constant' })
hi('@character.special', { link = 'Constant' })
hi('@character.printf', { link = 'Keyword' })
hi('@type', { link = 'Type' })
hi('@type.builtin', { link = 'Keyword' })
hi('@type.definition', { link = 'Type' })
hi('@type.qualifier', { link = 'Type' })
hi('@attribute', { link = 'Keyword' })
hi('@function', { link = 'Function' })
hi('@function.bash', { link = 'Type' })
hi('@function.builtin', { link = 'Function' })
hi('@function.call', { link = 'Function' })
hi('@function.call.bash', { link = 'Type' })
hi('@function.macro', { link = 'Function' })
hi('@function.method', { link = 'Function' })
hi('@function.method.call', { link = 'Function' })
hi('@constructor', { link = 'Type' })
hi('@constructor.lua', { link = 'Delimiter' })
hi('@operator', { link = 'Statement' })
hi('@keyword', { link = 'Keyword' })
hi('@keyword.coroutine', { link = 'Statement' })
hi('@keyword.function', { link = 'Keyword' })
hi('@keyword.type', { link = 'Keyword' })
hi('@keyword.operator', { link = 'Statement' })
hi('@keyword.import', { link = 'Include' })
hi('@keyword.repeat', { link = 'Statement' })
hi('@keyword.return', { link = 'Statement' })
hi('@keyword.debug', { link = 'Keyword' })
hi('@keyword.exception', { link = 'Statement' })
hi('@keyword.conditional', { link = 'Statement' })
hi('@keyword.conditional.ternary', { link = 'Statement' })
hi('@keyword.directive', { link = 'Statement' })
hi('@keyword.directive.define', { link = 'Statement' })
hi('@punctuation.delimiter', { link = 'Delimiter' })
hi('@punctuation.bracket', { link = 'Delimiter' })
hi('@punctuation.special', { link = 'Keyword' })
hi('@comment', { link = 'Comment' })
hi('@comment.documentation', { link = 'Comment' })
hi('@comment.error', { fg = c.diag_error })
hi('@comment.warning', { fg = c.diag_warning })
hi('@comment.todo', { link = 'Todo' })
hi('@comment.note', { fg = c.diag_hint })
hi('@markup.strong', { fg = c.purple, bold = true })
hi('@markup.italic', { link = 'Underlined' })
hi('@markup.strikethrough', { fg = c.base01, strikethrough = true })
hi('@markup.underline', { link = 'Underlined' })
hi('@markup.heading', { fg = c.blue, bold = true })
hi('@markup.heading.1', { fg = c.blue })
hi('@markup.heading.2', { fg = c.green })
hi('@markup.heading.3', { fg = c.yellow })
hi('@markup.heading.4', { fg = c.orange })
hi('@markup.heading.5', { fg = c.red })
hi('@markup.heading.6', { fg = c.purple })
hi('@markup.quote', { fg = c.green })
hi('@markup.math', { fg = c.purple })
hi('@markup.environment', { link = 'Comment' })
hi('@markup.link', { link = 'Underlined' })
hi('@markup.link.label', { link = 'Constant' })
hi('@markup.link.url', { link = 'Underlined' })
hi('@markup.raw', { fg = c.cyan })
hi('@markup.raw.block', { fg = c.base0 })
hi('@markup.list', { fg = c.orange })
hi('@markup.list.checked', { fg = c.green })
hi('@markup.list.unchecked', { fg = c.base01 })
hi('@diff.plus', { fg = c.git_add })
hi('@diff.minus', { fg = c.git_delete })
hi('@diff.delta', { fg = c.git_modify })
hi('@tag', { link = 'Tag' })
hi('@tag.attribute', { link = 'TagAttribute' })
hi('@tag.delimiter', { link = 'TagDelimiter' })

hi('@lsp.type.class', { link = 'Type' })
hi('@lsp.type.decorator', { link = 'Function' })
hi('@lsp.type.enum', { link = 'Type' })
hi('@lsp.type.enumMember', { link = 'Type' })
hi('@lsp.type.interface', { link = 'Type' })
hi('@lsp.type.macro', { link = '@function.builtin' })
hi('@lsp.type.namespace', { link = 'Type' })
hi('@lsp.type.parameter', { link = 'Parameter' })
hi('@lsp.type.property', { link = 'Property' })
hi('@lsp.type.struct', { link = 'Type' })
hi('@lsp.type.type', { link = 'Type' })
hi('@lsp.type.typeParameter', { link = 'Type' })
hi('@lsp.type.variable', { link = 'Identifier' })
hi('@lsp.typemod.variable.defaultLibrary', { link = 'Constant' })
hi('@lsp.typemod.variable.readonly', { link = 'Constant' })
hi('@lsp.typemod.variable.global', { link = 'Constant' })
hi('@lsp.typemod.keyword.documentation', { link = 'Keyword' })
hi('@lsp.typemod.class.documentation', { link = 'Type' })
hi('@lsp.typemod.property.readonly', { link = 'Constant' })
hi('DiagnosticError', { fg = c.diag_error })
hi('DiagnosticWarn', { fg = c.diag_warning })
hi('DiagnosticInfo', { fg = c.diag_info })
hi('DiagnosticHint', { fg = c.diag_hint })
hi('DiagnosticOk', { fg = c.diag_ok })
hi('DiagnosticVirtualTextError', { fg = c.diag_error })
hi('DiagnosticVirtualTextWarn', { fg = c.diag_warning })
hi('DiagnosticVirtualTextInfo', { fg = c.diag_info })
hi('DiagnosticVirtualTextHint', { fg = c.diag_hint })
hi('DiagnosticVirtualTextOk', { fg = c.diag_ok })
hi('DiagnosticUnderlineError', { fg = c.diag_error, underline = true, sp = c.diag_error })
hi('DiagnosticUnderlineWarn', { fg = c.diag_warning, underline = true, sp = c.diag_warning })
hi('DiagnosticUnderlineInfo', { fg = c.diag_info, underline = true, sp = c.diag_info })
hi('DiagnosticUnderlineHint', { fg = c.diag_hint, underline = true, sp = c.diag_hint })
hi('DiagnosticUnderlineOk', { fg = c.diag_ok, underline = true, sp = c.diag_ok })
hi('DiagnosticSignError', { fg = c.diag_error }) -- Used for "Error" signs in sign column.
hi('DiagnosticSignWarn', { fg = c.diag_warning }) -- Used for "Warn" signs in sign column.
hi('DiagnosticSignInfo', { fg = c.diag_info }) -- Used for "Info" signs in sign column.
hi('DiagnosticSignHint', { fg = c.diag_hint }) -- Used for "Hint" signs in sign column.
hi('DiagnosticSignOk', { fg = c.diag_ok })
hi('LspReferenceText', { fg = c.cyan, bg = c.mix_cyan })
hi('LspReferenceRead', { fg = c.green, bg = c.mix_green })
hi('LspReferenceWrite', { fg = c.green, bg = c.mix_green })
hi('LspInlayHint', { fg = c.base01 })
hi('LspInlayHint', { fg = color.shade(c.cyan, 3) })

hi('CmpItemKindText', { link = 'String' })
hi('CmpItemKindMethod', { link = 'Function' })
hi('CmpItemKindFunction', { link = 'Function' })
hi('CmpItemKindField', { link = 'Identifier' })
hi('CmpItemKindVariable', { link = 'Identifier' })
hi('CmpItemKindClass', { link = 'Type' })
hi('CmpItemKindInterface', { link = 'Type' })
hi('CmpItemKindModule', { link = 'Type' })
hi('CmpItemKindProperty', { link = 'Identifier' })
hi('CmpItemKindUnit', { link = 'Number' })
hi('CmpItemKindEnum', { link = 'Type' })
hi('CmpItemKindKeyword', { link = 'Keyword' })
hi('CmpItemKindSnippet', { link = 'Tag' })
hi('CmpItemKindColor', { link = 'Special' })
hi('CmpItemKindFile', { link = 'Identifier' })
hi('CmpItemKindReference', { link = 'Underlined' })
hi('CmpItemKindFolder', { link = 'Directory' })
hi('CmpItemKindEnumMember', { link = 'Constant' })
hi('CmpItemKindConstant', { link = 'Constant' })
hi('CmpItemKindStruct', { link = 'Identifier' })
hi('CmpItemKindEvent', { link = 'Function' })
hi('CmpItemKindOperator', { link = 'Operator' })
hi('CmpItemKindTypeParameter', { link = 'Type' })

hi('NeoTreeTitleBar', { fg = c.cyan, bg = c.mix_cyan })
hi('NeoTreeNormal', { fg = c.base0, bg = c.base03 })
hi('NeoTreeNormalNC', { link = 'NeoTreeNormal' })
hi('NeoTreeDotFile', { fg = c.base01 })
hi('NeoTreeGitIgnored', { link = 'NeoTreeDotFile' })
hi('NeoTreeFileStats', { link = 'NeoTreeDotFile' })
hi('NeoTreeDimText', { link = 'NeoTreeDotFile' })
hi('NeoTreeFileNameOpened', { link = 'Directory' })
hi('NeoTreeFloatBorder', { link = 'WinSeparator' })
hi('NeoTreeFloatTitle', { link = 'Title' })
hi('NeoTreeGitAdded', { fg = c.git_add })
hi('NeoTreeGitConflict', { fg = c.git_modify })
hi('NeoTreeGitDeleted', { fg = c.git_delete })
hi('NeoTreeGitModified', { fg = c.git_modify })
hi('NeoTreeGitUnstaged', { fg = c.git_modify })
hi('NeoTreeGitUntracked', { fg = c.git_modify })
hi('NeoTreeGitStaged', { fg = c.git_add })

hi('WhichKeyNormal', { fg = c.base0, bg = c.base03 })
hi('WhichKey', { link = 'Property' })
hi('WhichKeyDesc', { link = 'String' })
hi('WhichKeySeparator', { link = 'Keyword' })
hi('WhichKeyGroup', { link = 'Constant' })

hi('DashboardHeader', { fg = c.base01 })
hi('DashboardFooter', { fg = c.purple })
hi('DashboardDesc', { link = 'Directory' })
hi('DashboardKey', { link = 'Keyword' })
hi('DashboardIcon', { link = 'Directory' })
hi('DashboardShotCut', { fg = c.base0 })

hi('GitSignsAdd', { fg = c.git_add })
hi('GitSignsChange', { fg = c.git_modify })
hi('GitSignsDelete', { fg = c.git_delete })

hi('TelescopeSelection', { fg = c.blue, bg = c.base02 })
hi('TelescopeSelectionCaret', { fg = c.blue, bg = c.base02 })
hi('TelescopeMultiIcon', { fg = c.blue })
hi('TelescopeNormal', { fg = c.base0, bg = c.base03 })
hi('TelescopePreviewNormal', { link = 'TelescopeNormal' })
hi('TelescopePromptNormal', { link = 'TelescopeNormal' })
hi('TelescopeResultsNormal', { link = 'TelescopeNormal' })
hi('TelescopeBorder', { link = 'FloatBorder' })
hi('TelescopePromptBorder', { link = 'TelescopeBorder' })
hi('TelescopeResultsBorder', { link = 'TelescopeBorder' })
hi('TelescopePreviewBorder', { link = 'TelescopeBorder' })
hi('TelescopeTitle', { link = 'FloatTitle' })
hi('TelescopePromptTitle', { link = 'TelescopeTitle' })
hi('TelescopeResultsTitle', { link = 'TelescopeTitle' })
hi('TelescopePreviewTitle', { link = 'TelescopeTitle' })
hi('TelescopeMatching', { fg = c.cyan, bg = c.mix_cyan })
hi('TelescopePreviewMatch', { link = 'TelescopeMatching' })
hi('TelescopePromptCounter', { link = 'NonText' })
hi('TelescopePromptPrefix', { fg = c.cyan })

hi('HopNextKey', { fg = c.purple })
hi('HopNextKey1', { fg = c.blue })
hi('HopNextKey2', { fg = c.cyan })
hi('HopUnmatched', { fg = c.base01 })

hi('BufferLineFill', { bg = c.base02 })
hi('BufferLineBufferSelected', { fg = c.base0 })
hi('BufferLineSeparator', { fg = c.base02 })
hi('BufferLineSeparatorSelected', { fg = c.base02 })
hi('BufferLineSeparatorVisible', { fg = c.base02 })

hi('RenderMarkdownH1Bg', { fg = c.blue, bg = c.mix_blue })
hi('RenderMarkdownH2Bg', { fg = c.green, bg = c.mix_green })
hi('RenderMarkdownH3Bg', { fg = c.yellow, bg = c.mix_yellow })
hi('RenderMarkdownH4Bg', { fg = c.orange, bg = c.mix_orange })
hi('RenderMarkdownH5Bg', { fg = c.red, bg = c.mix_red })
hi('RenderMarkdownH6Bg', { fg = c.purple, bg = c.mix_purple })
hi('RenderMarkdownCode', { bg = c.base03 })

return M
