local map = vim.keymap.set
local opts = { silent = true }

map('x', '<a-t>', ':!gen table<cr>')
map('x', '<a-b>', ':!gen br<cr>')
map('x', '<a-e>', ':!gen en<cr>')
map('x', '<a-g>', ':!gen grammar<cr>')
map('n', '<tab>', '<cmd>WindowPick<cr>', opts)
map('n', '<c-left>', '<c-w>h', opts)
map('n', '<c-right>', '<c-w>l', opts)
map('n', '<c-up>', '<c-w>k', opts)
map('n', '<c-down>', '<c-w>j', opts)
map('n', 'gt', '<cmd>MarkdownToggleTask<cr>', opts)
map('n', '<F3>', '<cmd>Runner<cr>', opts)
map('n', '+', '<c-a>', opts)
map('n', '-', '<c-x>', opts)
map('n', '<M-left>', '<cmd>BufferLineCyclePrev<cr>', opts)
map('n', '<M-right>', '<cmd>BufferLineCycleNext<cr>', opts)
map('n', '<M-down>', '<cmd>bd<cr>', opts)
map('n', '<M-up>', '<cmd>BufferLinePick<cr>', opts)
