#!/bin/bash

read -n1 -p "[ACTION] - Would you like to continue with the install (y/n): " INST

if [[ $INST == "y" ]]; then
    echo "Installation will proceed."
    # Perform installation steps
else
    echo "Installation canceled."
    exit 1
    # Perform cancellation steps or exit the script
fi

# install paru
sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si

## install stow
paru -S stow

## stow
stow ~/dotfiles/hyprland
stow ~/dotfiles/waybar
stow ~/dotfiles/kitty
stow ~/dotfiles/fonts
stow ~/dotfiles/rofi

## install hyprland
paru -S hyprland-git \
         kitty \
         dunst \
         mako \
         pipewire \
         wireplumbe \
         pavucontrol \
         xdg-desktop-portal-hyprland \
         qt5-wayland \
         qt5ct \
         qt6-wayland \
         grim \
         slurp \
         cliphis \t
         thunar \
         thunar-archive-plugin \
         thunar-media-tags-plugin \
         thunar-archive-plugin \
         thunar-volman \
         gvfs \
         swww \
         wlogout \
         evince-light \

## install rofi
paru -S rofi-lbonn-wayland-git

## install waybar
paru -S waybar-hyprland \
        network-manager-applet \
        jq

Hyprland