local M = {}
M.base_30 = {
  white = '#dee1e6',
  darker_black = '#1a1a1a',
  black = '#1E1E1E',
  black2 = '#252525',
  one_bg = '#282828',
  one_bg2 = '#313131',
  one_bg3 = '#3a3a3a',
  grey = '#444444',
  grey_fg = '#4e4e4e',
  grey_fg2 = '#585858',
  light_grey = '#626262',
  red = '#D16969',
  baby_pink = '#D16969',
  pink = '#bb7cb6',
  line = '#2e2e2e',
  green = '#6A9955',
  vibrant_green = '#bfd8b2',
  blue = '#4FC1FF',
  nord_blue = '#60a6e0',
  yellow = '#DCDCAA',
  sun = '#ffcc77',
  purple = '#c68aee',
  dark_purple = '#b77bdf',
  teal = '#4294D6',
  orange = '#CE9178',
  cyan = '#4EC9B0',
  statusline_bg = '#242424',
  lightbg = '#303030',
  pmenu_bg = '#60a6e0',
  folder_bg = '#0078d4',
}

M.base_16 = {
  base00 = '#1e1e1e',
  base01 = '#181818',
  base02 = '#264f78',
  base03 = '#808080',
  base04 = '#c8c8c8',
  base05 = '#c8c8c8',
  base06 = '#c8c8c8',
  base07 = '#444444',
  base08 = '#9CDCFE',
  base09 = '#4FC1FF',
  base0A = '#4EC9B0',
  base0B = '#CE9178',
  base0C = '#569cd6',
  base0D = '#DCDCAA',
  base0E = '#569cd6',
  base0F = '#569cd6',
}

M.polish_hl = {
  treesitter = {
    ['@keyword.function'] = { fg = M.base_30.purple },
    ['@keyword.repeat'] = { link = '@keyword.function' },
    ['@keyword.return'] = { link = '@keyword.function' },
    ['@keyword.conditional'] = { link = '@keyword.function' },
    ['@keyword.conditional.ternary'] = { link = '@keyword.function' },
    ['@keyword.directive'] = { link = '@keyword.function' },
    ['@keyword.directive.define'] = { link = '@keyword.function' },
    ['@keyword.exception'] = { link = '@keyword.function' },
    ['@keyword.coroutine'] = { link = '@keyword.function' },
    ['@keyword.operator'] = { link = '@keyword.function' },
    ['@type.builtin'] = { link = 'Keyword' },
    ['@tag'] = { fg = M.base_30.nord_blue },
    ['@constant.html'] = { link = '@tag' },
    ['@constant.css'] = { fg = M.base_30.orange },
    ['@type.css'] = { fg = M.base_30.orange },
    ['@keyword.directive.css'] = { link = '@Keyword.function' },
    ['@constant.scss'] = { link = '@constant.css' },
    ['@type.scss'] = { link = '@type.css' },
    ['@keyword.directive.scss'] = { link = '@keyword.directive.css' },
    ['@markup.strong'] = { fg = M.base_30.blue, bold = true },
    ['@markup.italic'] = { fg = M.base_30.blue, italic = true },
    ['@markup.quote'] = { fg = M.base_30.green },
    ['@markup.heading'] = { fg = M.base_30.blue },
    ['@markup.heading.1'] = { fg = M.base_30.blue },
    ['@markup.heading.2'] = { fg = M.base_30.nord_blue },
    ['@markup.heading.3'] = { fg = M.base_30.yellow },
    ['@markup.heading.4'] = { fg = M.base_30.orange },
    ['@markup.heading.5'] = { fg = M.base_30.cyan },
    ['@markup.heading.6'] = { fg = M.base_30.sun },
    ['@variable'] = { link = 'Variable' },
    ['@constant'] = { link = 'Constant' },
    ['@comment'] = { fg = M.base_30.green },
    ['@number'] = { link = 'Number' },
  },
  syntax = {
    Constant = { fg = M.base_16.base09 },
    Variable = { fg = M.base_16.base08 },
    Include = { fg = M.base_30.purple },
    Number = { fg = M.base_30.vibrant_green },
  },
  semantic_tokens = {
    ['@lsp.type.variable'] = { link = 'Variable' },
    ['@lsp.mod.readonly'] = { link = 'Constant' },
    ['@lsp.mod.global'] = { link = 'Constant' },
    ['@lsp.typemod.variable.globalScope'] = { link = 'Constant' },
    ['@lsp.typemod.variable.global'] = { link = 'Constant' },
    ['@lsp.typemod.variable.defaultLibrary'] = { link = 'Constant' },
  },
  cmp = {
    CmpItemKindField = { link = '@property' },
    CmpItemKindFile = { link = 'Normal' },
    CmpItemKindFolder = { link = 'Directory' },
    CmpItemKindKeyword = { link = '@keyword' },
    CmpItemKindFunction = { fg = M.base_30.purple },
    CmpItemKindMethod = { fg = M.base_30.purple },
  },
}

M.type = 'dark'

M = require('base46').override_theme(M, 'abc')

return M
