local codicons_preset = {
  File = ' ',
  Module = ' ',
  Namespace = ' ',
  Package = ' ',
  Class = ' ',
  Method = ' ',
  Property = ' ',
  Field = ' ',
  Constructor = ' ',
  Enum = ' ',
  Interface = ' ',
  Function = ' ',
  Variable = ' ',
  Constant = ' ',
  String = ' ',
  Number = ' ',
  Boolean = ' ',
  Array = ' ',
  Object = ' ',
  Key = ' ',
  Null = ' ',
  EnumMember = ' ',
  Struct = ' ',
  Event = ' ',
  Operator = ' ',
  TypeParameter = ' ',
}
local default_preset = {
  File = '󰈙 ',
  Module = ' ',
  Namespace = '󰌗 ',
  Package = ' ',
  Class = '󰌗 ',
  Method = '󰆧 ',
  Property = ' ',
  Field = ' ',
  Constructor = ' ',
  Enum = '󰕘',
  Interface = '󰕘',
  Function = '󰊕 ',
  Variable = '󰆧 ',
  Constant = '󰏿 ',
  String = '󰀬 ',
  Number = '󰎠 ',
  Boolean = '◩ ',
  Array = '󰅪 ',
  Object = '󰅩 ',
  Key = '󰌋 ',
  Null = '󰟢 ',
  EnumMember = ' ',
  Struct = '󰌗 ',
  Event = ' ',
  Operator = '󰆕 ',
  TypeParameter = '󰊄 ',
}

return {
  'SmiteshP/nvim-navic',
  opts = {
    icons = vim.g.neovide and codicons_preset or default_preset,
    highlight = true,
  },
}
