[general]
import = ["~/.config/alacritty/doom-one.toml"]

[font]
normal = { family = "JetBrainsMonoNLNerdFont", style = "Regular" }
bold = { family = "JetBrainsMonoNLNerdFont" }
bold_italic = { family = "JetBrainsMonoNLNerdFont" }
italic = { family = "JetBrainsMonoNLNerdFont" }
size = 16

[env]
TERM = "xterm-256color"
