return {
  {
    'maxmx03/onedarkpro.nvim',
    lazy = false,
    priority = 1000,
    config = function()
      require('onedarkpro').setup {
        styles = {
          comments = 'italic',
          keywords = 'italic',
          functions = 'italic',
          variables = 'italic',
          conditionals = 'italic',
        },
        highlights = {
          HopNextKey = { fg = '${purple}', bg = 'NONE' },
          HopNextKey1 = { fg = '${blue}', bg = 'NONE' },
          CmpItemKindText = { reverse = true },
          CmpItemKindMethod = { reverse = true },
          CmpItemKindFunction = { reverse = true },
          CmpItemKindConstructor = { reverse = true },
          CmpItemKindField = { reverse = true },
          CmpItemKindVariable = { reverse = true },
          CmpItemKindClass = { reverse = true },
          CmpItemKindInterface = { reverse = true },
          CmpItemKindModule = { reverse = true },
          CmpItemKindProperty = { reverse = true },
          CmpItemKindUnit = { reverse = true },
          CmpItemKindValue = { reverse = true },
          CmpItemKindEnum = { reverse = true },
          CmpItemKindKeyword = { reverse = true },
          CmpItemKindSnippet = { reverse = true },
          CmpItemKindColor = { reverse = true },
          CmpItemKindFile = { reverse = true },
          CmpItemKindReference = { reverse = true },
          CmpItemKindFolder = { reverse = true },
          CmpItemKindEnumMember = { reverse = true },
          CmpItemKindConstant = { reverse = true },
          CmpItemKindStruct = { reverse = true },
          CmpItemKindEvent = { reverse = true },
          CmpItemKindOperator = { reverse = true },
          CmpItemKindTypeParameter = { reverse = true },
          DashboardHeader = { fg = '${comment}' },
          DashboardCenter = { fg = '${fg}' },
          DashboardFooter = { fg = '${comment}' },
          DashboardProjectTitle = { link = 'Title' },
          DashboardProjectTitleIcon = { link = 'Title' },
          DashboardProjectIcon = { fg = '${purple}' },
          DashboardMruTitle = { link = 'Title' },
          DashboardMruIcon = { link = 'Title' },
          DashboardFiles = { fg = '${fg}' },
          DashboardShotCutIcon = { fg = '${blue}' },
          DashboardDesc = { fg = '${blue}' },
          DashboardKey = { fg = '${purple}' },
          DashboardIcon = { fg = '${blue}' },
          DashboardShotCut = { fg = '${purple}' },
          ColorColumn = { fg = '${float_bg}', bg = '${float_bg}' },
          NvimTreeNormal = { bg = '${float_bg}' },
          NvimTreeWinSeparator = { fg = '${float_bg}', bg = '${float_bg}' },
          ['@function.builtin'] = { link = '@function' },
          PMenuSel = { fg = '${green}', reverse = true },
          PmenuThumb = { bg = '${green}' },
          CmpWinSeparator = { fg = '${float_bg}', bg = '${float_bg}' },
        },
      }

      vim.cmd.colorscheme 'onedark'
    end,
  },
}
