#!/usr/bin/env bash

DEPENDENCIES=(
  git
  luarocks # optional
  neovim
  python-pynvim
  gcc
  ripgrep
  xclip
  curl
  unzip
  gzip
  go
)

# BTW
paru -S "${DEPENDENCIES[@]}" --noconfirm

if [[ -n $(command -v cargo) ]]; then
  cargo install tree-sitter-cli
else
  echo "You need to install cargo to install tree-sitter-cli"
  echo "Then run cargo install tree-sitter-cli"
fi
echo "Don't forget to install nodejs: https://nodejs.org/pt/download"
