#!/usr/bin/env bash

updates_repo=$(checkupdates 2>/dev/null | wc -l)
updates_aur=$(yay -Qum --aur 2>/dev/null | wc -l)

total_updates=$((updates_repo + updates_aur))

if [ "$total_updates" -gt 0 ]; then
  echo "󰮭 $total_updates updates "
else
  echo ""
fi
